#use minima theme
remote_theme: "jekyll/minima@f1a2af4"
author :
  name : "tayoky"
  email : "tayoky4848@gmail.com"


minima :
  skin : auto
  
  nav_pages:
    - index.html
    - user.html
    - syscall
    - kernel

#social media link
  social_links:
    - title : "tayoky on github"
      icon : github
      url : "https://github.com/tayoky"
