name: 'TBuild StanixOS test'

on:
  - push
  - pull_request

jobs:
  build-stanix:
    runs-on: ubuntu-latest

    steps:
    - name: Set up depencies
      run: sudo apt install build-essential bison flex texinfo libmpc-dev libgmp-dev libmpfr-dev automake autoconf gdisk mtools xorriso nasm -y
        
    - name: Fix depencies
      run: |
        rm -rf limine ports tlibc
        git clone https://github.com/limine-bootloader/limine.git
        git clone https://github.com/tayoky/ports.git
        git clone https://github.com/tayoky/tlibc.git

    - name: Build stanix
      run: |
        . add-to-path.sh
        ./configure
        make
        ./essential-ports.sh
        make
        ./build-toolchain.sh